spring:
  redis:
    host: 192.168.226.10
    port: 6379

  datasource:
    url: jdbc:mysql://192.168.226.10:3306/security?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root